# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.displayedE10SNotice", 4);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150331030204");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1282);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150331030204");
user_pref("browser.startup.homepage_override.mstone", "40.0a1");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1427934907677");
user_pref("datareporting.policy.firstRunTime", "1427848507677");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1018);
user_pref("datareporting.sessions.current.main", 58);
user_pref("datareporting.sessions.current.sessionRestored", 1212);
user_pref("datareporting.sessions.current.startTime", "1427849536443");
user_pref("datareporting.sessions.current.totalTime", 5);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1427848507415,\"a\":1,\"t\":2,\"c\":true,\"m\":56,\"fp\":-1,\"sr\":-1}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:40.0a1");
user_pref("extensions.lastAppVersion", "40.0a1");
user_pref("extensions.lastPlatformVersion", "40.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/FirefoxNightly.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"40.0a1\",\"st\":1427843424000,\"mt\":1427843424000}}}");
user_pref("gecko.buildID", "20150331030204");
user_pref("gecko.mstone", "40.0a1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1427849536);
user_pref("toolkit.telemetry.previousBuildID", "20150331030204");
user_pref("browser.safebrowsing.debug",true);
user_pref("browser.safebrowsing.provider.mozilla.updateURL","http://localhost:13000");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime","1");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime","1");
